### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#252]
- [x] remove core apps verification
- [x] support brevented apps in sdcard
- [x] remove self priority
- [x] remove pay packages
- [x] safe processes use home instead of receiver
