### ISSUE TITLE
TODO List since 3.2.1p1

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#328]
- [x] fix stderr / stdout in exec command (@vvb2060 )
- [x] fix may foregroundServiceNoNotification audio apps (#315)
- [x] remove dependency on show os apps
- [x] add auto-aggressive whitelist
- [x] use navigation drawer
