### ISSUE TITLE
TODO List since 3.2.5.8

### ISSUE THREAD

**Issue by liudongmiao** [brevent/Brevent#360]
## app ## 
- [x] remove diagnosis
- [x] add theme
   - [x] aosp
   - [x] pixel
   - [x] jike yellow
   - [x] ~coolapk~(play) green
   - [x] nankai purple
   - [x] amoled black (experimental)
- [x] wechat, only for china
   - [x] login
   - [x] payment
   - [x] promotion code
- [x] ~allow sync in android p~
   - [x] ~app standby bucket~
   - [x] ~appops: background, any background~

## non app ##
- [x] update user guide (chinese)
- [x] landing page (main chinese)

**Comment by Zxilly** [comment]
## 可以参与guide的写作吗

**Comment by liudongmiao** [comment]
@Zxilly 请黑阈内使用邮件与我联系，谢谢。
